platform: 'illumina'

library: 'WES-Nextera-Rapid-Capture'

genotyping_mode: 'DISCOVERY'

stand_emit_conf: 10

stand_call_conf: 30

hg: '/data_ref/human_g1k_v37.fasta'

indels_ref: '/data_ref/Mills_and_1000G_gold_standard.indels.b37.vcf'

dbsnp: '/data_ref/dbsnp_138.b37.vcf'

cpu_type: 'xeond'

n_sim: '1' 

threads: '1'

n_cpu: '1'

#Mandatory
gatk: '/GenomeAnalysisTK.jar'
#gatk: '/mnt/avoton/biofisici/opt_local_gatk/source/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar'