platform: 'illumina'

library: 'WES-Nextera-Rapid-Capture'

hap-caller:
    genotyping_mode: 'DISCOVERY'
    stand_emit_conf: 10
    stand_call_conf: 30

hard-filter:
    snps: '--filterExpression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || HaplotypeScore > 13.0 || MappingQualityRankSum < -12.5 || ReadPosRankSum < -8.0" --filterName "snp_hardFilter"'
    indels: '--filterExpression "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0" --filterName "indel_hardFilter"'

hg: '/data_ref/human_g1k_v37.fasta'

indels_ref: '/data_ref/Mills_and_1000G_gold_standard.indels.b37.vcf'

dbsnp: '/data_ref/dbsnp_138.b37.vcf'

cpu_type: 'xeond'

n_sim: '1' 

threads: '1'

n_cpu: '1'

#Mandatory

gatk: '/GenomeAnalysisTK.jar'
#gatk: '/mnt/avoton/biofisici/opt_local_gatk/source/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar'
convert2annovar: '/annovar/annovar/convert2annovar.pl'
annovar: '/annovar/annovar/annotate_variation.pl'
humandb: '/annovar/annovar/humandb'
build_ver: 'hg19'
dbsnp_ver: 'snp138'
kg_ver: '1000g2012apr_all'
mitochondrial_ver: 'GRCh37_MT'